version: 0.1.{build}

platform:
  - x64
configuration:
  - Debug

before_build:
  # hack to stop sea of Xamarin (which isn't being used at all) warnings
  # during the cmake install
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

  - md build\Win64 
  - cd build\Win64
  - cmake -G "Visual Studio 14 2015 Win64" ..\.. 
  - cmake -DCMAKE_BUILD_TYPE=%configuration% -DCMAKE_INSTALL_PREFIX=publish .
  - cd ..\..

build_script:
  - cd build\Win64
  - cmake --build . --target install --config %configuration%
  - cd ..\..

after_build:
  - cd build\Win64\publish
  - 7z a dimapp-latest.zip include lib
  - cd ..\..\..

artifacts:
  - path: build\Win64\publish\dimapp-latest.zip
    name: dimapp
    type: zip

test_script:
  - build\Win64\bin\charbuf
  - build\Win64\bin\hpack
  - build\Win64\bin\http
  - build\Win64\bin\pargen --test
  - build\Win64\bin\xml --test

#deploy:
#  tag: dimapp-latest
#  description: continuous trunk build - $(appveyor_build_version)
#  provider: GitHub
#  auth_token:
#    secure: yheCA/FJ+f7CL84HoPf9MapOlDZQmrGyiqlwFeeIhxvdOudQisUdOyZuWfwq3lUU
#  prerelease: true
#  draft: false
#  force_update: true
