# Copyright Glen Knowles 2016 - 2019.
# Distributed under the Boost Software License, Version 1.0.
version: 0.1.{build}
image: Visual Studio 2019

environment:
  matrix:
    - toolset: v142
platform:
  - x64
configuration:
  - Debug

build_script:
  - git submodule update --init
  - md build
  - cd build
  - cmake -G "Visual Studio 16 2019" -A %platform% -T %toolset% ..
  - cmake . -DCMAKE_BUILD_TYPE=%configuration%
        -DCMAKE_INSTALL_PREFIX=publish
        -DINSTALL_LIBS:BOOL=ON
  - cmake --build . --target install --config %configuration%
  - cd publish
  - 7z a dimapp-latest.zip include lib
  - cd ..\..

artifacts:
  - path: build\publish\dimapp-latest.zip
    name: dimapp
    type: zip

test_script:
  - bin\bitview
  - bin\charbuf
  - bin\file
  - bin\hpack
  - bin\http
  - bin\json --test
  - bin\list
  - bin\math
  - bin\msgpack
  - bin\pargen --test
  - bin\path
  - bin\str
  - bin\strtrie --test
  - bin\time
  - bin\tokentable
  - bin\uset
  - bin\xml --test
