version: 0.1.{build}

platform:
  - x64
configuration:
  - Debug

build:
  parallel: true
  project: tismet.sln
  verbosity: minimal

test_script:
  - lib\dim\bin\cmdline
  - lib\dim\bin\hpack
  - lib\dim\bin\http

after_build:
  - 7z a tismet-v%appveyor_build_version%.zip bin\*.exe bin\*.pdb

artifacts:
  - path: tismet-v$(appveyor_build_version).zip
    name: tismet
    type: zip
#  - path: bin\*.exe
#  - path: bin\*.pdb

deploy:
  tag: tismet-v$(appveyor_build_version)
  description: continuous trunk build
  provider: GitHub
  auth_token:
    secure: yheCA/FJ+f7CL84HoPf9MapOlDZQmrGyiqlwFeeIhxvdOudQisUdOyZuWfwq3lUU
  prerelease: true
  draft: true
