# Copyright Glen Knowles 2016 - 2021.
# Distributed under the Boost Software License, Version 1.0.
#
# appveyor.yml
#
version: "{build}"
image: Visual Studio 2019 Preview

environment:
  matrix:
    - toolset: v142
      generator: Visual Studio 16 2019
platform:
  - x64
configuration:
  - Debug
  - Release

build_script:
  - git submodule update --init
  - md build
  - cd build
  - cmake -G "%GENERATOR%" -A %PLATFORM% -T %TOOLSET% ..
  - cmake . -DCMAKE_BUILD_TYPE=%CONFIGURATION%
        -DCMAKE_INSTALL_PREFIX=publish
        -DINSTALL_LIBS:BOOL=ON
  - cmake --build . --target install --config %CONFIGURATION%
  - cd publish
  - 7z a dimapp-latest.zip include lib
  - cd ..\..

artifacts:
  - path: build\publish\dimapp-latest.zip
    name: dimapp

test_script:
  - bin\bitview
  - bin\charbuf
  - bin\file
  - bin\hpack
  - bin\http
  - bin\json --test
  - bin\list
  - bin\math
  - bin\msgpack
  - bin\pargen --test
  - bin\path
  - bin\str
# - bin\strtrie --test
  - bin\time
  - bin\tokentable
  - bin\uset
  - bin\xml --test
