version: 0.1.{build}

platform:
  - x64
configuration:
  - Debug

build:
  parallel: true
  project: dimapp.sln
  verbosity: minimal

after_build:
  - 7z a dimapp-latest.zip bin\*.exe bin\*.pdb

artifacts:
  - path: dimapp-latest.zip
    name: dimapp
    type: zip

test_script:
  - bin\hpack
  - bin\http
  - bin\pargen --test
  - bin\xml --test

deploy:
  tag: dimapp-latest
  description: continuous trunk build - $(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: yheCA/FJ+f7CL84HoPf9MapOlDZQmrGyiqlwFeeIhxvdOudQisUdOyZuWfwq3lUU
  prerelease: true
  draft: false
  force_update: true
