# generated by make process
# pch.cpp
# pch.h
# winaddress.cpp
# winconsole.cpp
# winerror.cpp
# winfile.cpp
# winint.h
# winiocp.cpp
# winsock.cpp
# winsockacc.cpp
# winsockbuf.cpp
# winsockconn.cpp
# winsockint.h
# winsync.cpp
# wintime.cpp
