// jsonparseint.h
// Generated by pargen 2.1.3 at 2018-05-07T11:55:14-0700
// clang-format off
#pragma once

#include "jsonparsebaseint.h"

namespace Dim::Detail {


/****************************************************************************
*
*   JsonParser
*
***/

class JsonParser : public JsonParserBase {
public:
    using JsonParserBase::JsonParserBase;

    bool parse (char const src[]);
    size_t errpos () const { return m_errpos; }

private:
    bool stateArrayTail (char const *& src);
    bool stateObjectTail (char const *& src);

    // Events
    bool onArrayStart ();
    bool onArrayEnd ();
    bool onEBkspEnd ();
    bool onEBslashEnd ();
    bool onECrEnd ();
    bool onEDquoteEnd ();
    bool onEFeedEnd ();
    bool onENlEnd ();
    bool onESlashEnd ();
    bool onETabEnd ();
    bool onEscapeNumHexChar (char ch);
    bool onEscapeNumberEnd ();
    bool onExpMinusEnd ();
    bool onExpNumChar (char ch);
    bool onFalseEnd ();
    bool onFracNumChar (char ch);
    bool onIntMinusEnd ();
    bool onIntNumChar (char ch);
    bool onMemberNameEnd ();
    bool onNullEnd ();
    bool onNvalEnd ();
    bool onObjectStart ();
    bool onObjectEnd ();
    bool onStrTextStart (char const * ptr);
    bool onSvalEnd ();
    bool onTrueEnd ();
    bool onUnescapedChar (char ch);

    // Data members
    size_t m_errpos{0};
};

} // namespace
