; Copyright Glen Knowles 2016 - 2018.
; Distributed under the Boost Software License, Version 1.0.
;
; tests.abnf - pargen
;
%root = t2
%api.prefix = Test
%api.parser.file.h = test-out.h         ; defaults to <%api.prefix>parse.h
%api.parser.file.cpp = test-out.cpp     ; defaults to <%api.prefix>parse.cpp

t1 = t1-param *(RWS t1-param)
t1-param = RWS { Start, End }

; t2 - requires infinite stack. A series of 10 alphas, may be either 1 (if
; followed by quote) or 10 (if followed by EOF) params
t2 = *t2-param
t2-param = *(1*ALPHA DQUOTE) ALPHA { Start, End }
