// cmdline-argv.h
// Generated by pargen at 2016-09-23T13:27:00-0700
// clang-format off
#pragma once


/****************************************************************************
*
*   Parser event notifications
*   Clients inherit from this class to make process parsed results
*
***/

class IArgvParserNotify {
public:
    virtual ~IArgvParserNotify () {}

    virtual bool onStart () { return true; }
    virtual bool onEnd () { return true; }

    virtual bool onParamStart (const char * ptr) { return true; }
    virtual bool onParamEnd (const char * eptr) { return true; }
};


/****************************************************************************
*
*   ArgvParser
*
***/

class ArgvParser {
public:
    ArgvParser (IArgvParserNotify * notify) : m_notify(notify) {}
    ~ArgvParser () {}

    bool parse (const char src[]);

private:
    IArgvParserNotify * m_notify{nullptr};
};
