// cmdline-argv.cpp
// Generated by pargen at 2016-09-23T13:27:00-0700
// clang-format off
#include "pch.h"
#pragma hdrstop


/****************************************************************************
*
*   ArgvParser
*
*   Normalized ABNF of syntax:
*   %root = line 
*   BSLASH = %x5c 
*   DQUOTE = %x22 
*   HTAB = %x9 
*   OWS = *( SP / HTAB ) 
*   RWS = 1*( SP / HTAB ) 
*   SP = %x20 
*   active-quote = ( *bslash-pair DQUOTE ) 
*   bslash-pair = ( BSLASH BSLASH ) 
*   dquote-pair = ( DQUOTE DQUOTE ) 
*   escaped-quote = ( BSLASH *bslash-pair DQUOTE ) 
*   fully-quoted = ( active-quote quoted active-quote ) 
*   half-quoted = ( active-quote quoted ) 
*   line = ( OWS param *( RWS param ) *1( RWS open-param ) OWS ) 
*   open-param = ( *( unquoted / fully-quoted ) half-quoted *BSLASH ) { Start, 
*       End, As=param } 
*   param = ( *( unquoted / fully-quoted ) *BSLASH ) { Start, End } 
*   pchar = ( %x21 / %x23 / %x24 / %x25 / %x26 / %x27 / %x28 / %x29 / %x2a / 
*       %x2b / %x2c / %x2d / %x2e / %x2f / %x30 / %x31 / %x32 / %x33 / %x34 / 
*       %x35 / %x36 / %x37 / %x38 / %x39 / %x3a / %x3b / %x3c / %x3d / %x3e / 
*       %x3f / %x40 / %x41 / %x42 / %x43 / %x44 / %x45 / %x46 / %x47 / %x48 / 
*       %x49 / %x4a / %x4b / %x4c / %x4d / %x4e / %x4f / %x50 / %x51 / %x52 / 
*       %x53 / %x54 / %x55 / %x56 / %x57 / %x58 / %x59 / %x5a / %x5b / %x5d / 
*       %x5e / %x5f / %x60 / %x61 / %x62 / %x63 / %x64 / %x65 / %x66 / %x67 / 
*       %x68 / %x69 / %x6a / %x6b / %x6c / %x6d / %x6e / %x6f / %x70 / %x71 / 
*       %x72 / %x73 / %x74 / %x75 / %x76 / %x77 / %x78 / %x79 / %x7a / %x7b / 
*       %x7c / %x7d / %x7e ) 
*   ptext = 1*( *1BSLASH pchar ) 
*   quoted = 1*( ptext / dquote-pair / escaped-quote / RWS ) 
*   unquoted = 1*( ptext / escaped-quote ) 
*
***/

//===========================================================================
bool ArgvParser::parse (const char src[]) {
    const char * ptr = src;
    char ch;
    goto state2;

state0: 
    // <FAILED>
    return false;

state1:
    // 1: <DONE>
    return true;

state2:
    // 2: 
    ch = *ptr++;
    switch (ch) {
    case 9: case ' ': 
        goto state3;
    case '!': case '#': case '$': case '%': case '&': case '\'':
    case '(': case ')': case '*': case '+': case ',': case '-':
    case '.': case '/': case '0': case '1': case '2': case '3':
    case '4': case '5': case '6': case '7': case '8': case '9':
    case ':': case ';': case '<': case '=': case '>': case '?':
    case '@': case 'A': case 'B': case 'C': case 'D': case 'E':
    case 'F': case 'G': case 'H': case 'I': case 'J': case 'K':
    case 'L': case 'M': case 'N': case 'O': case 'P': case 'Q':
    case 'R': case 'S': case 'T': case 'U': case 'V': case 'W':
    case 'X': case 'Y': case 'Z': case '[': case ']': case '^':
    case '_': case '`': case 'a': case 'b': case 'c': case 'd':
    case 'e': case 'f': case 'g': case 'h': case 'i': case 'j':
    case 'k': case 'l': case 'm': case 'n': case 'o': case 'p':
    case 'q': case 'r': case 's': case 't': case 'u': case 'v':
    case 'w': case 'x': case 'y': case 'z': case '{': case '|':
    case '}': case '~': 
        goto state90;
    case '"': 
        goto state127;
    case '\\': 
        goto state128;
    }
    goto state0;

state3:
    // 3: ^I
    // 7: ^I!^I^I
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state1;
    case 9: case ' ': 
        goto state3;
    case '!': case '#': case '$': case '%': case '&': case '\'':
    case '(': case ')': case '*': case '+': case ',': case '-':
    case '.': case '/': case '0': case '1': case '2': case '3':
    case '4': case '5': case '6': case '7': case '8': case '9':
    case ':': case ';': case '<': case '=': case '>': case '?':
    case '@': case 'A': case 'B': case 'C': case 'D': case 'E':
    case 'F': case 'G': case 'H': case 'I': case 'J': case 'K':
    case 'L': case 'M': case 'N': case 'O': case 'P': case 'Q':
    case 'R': case 'S': case 'T': case 'U': case 'V': case 'W':
    case 'X': case 'Y': case 'Z': case '[': case ']': case '^':
    case '_': case '`': case 'a': case 'b': case 'c': case 'd':
    case 'e': case 'f': case 'g': case 'h': case 'i': case 'j':
    case 'k': case 'l': case 'm': case 'n': case 'o': case 'p':
    case 'q': case 'r': case 's': case 't': case 'u': case 'v':
    case 'w': case 'x': case 'y': case 'z': case '{': case '|':
    case '}': case '~': 
        goto state4;
    case '"': 
        goto state49;
    case '\\': 
        goto state50;
    }
    goto state0;

state4:
    // 4: ^I!
    // 8: ^I!^I^I!
    m_notify->onParamStart(ptr - 1);
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state5;
    case 9: case ' ': 
        goto state6;
    case '!': case '#': case '$': case '%': case '&': case '\'':
    case '(': case ')': case '*': case '+': case ',': case '-':
    case '.': case '/': case '0': case '1': case '2': case '3':
    case '4': case '5': case '6': case '7': case '8': case '9':
    case ':': case ';': case '<': case '=': case '>': case '?':
    case '@': case 'A': case 'B': case 'C': case 'D': case 'E':
    case 'F': case 'G': case 'H': case 'I': case 'J': case 'K':
    case 'L': case 'M': case 'N': case 'O': case 'P': case 'Q':
    case 'R': case 'S': case 'T': case 'U': case 'V': case 'W':
    case 'X': case 'Y': case 'Z': case '[': case ']': case '^':
    case '_': case '`': case 'a': case 'b': case 'c': case 'd':
    case 'e': case 'f': case 'g': case 'h': case 'i': case 'j':
    case 'k': case 'l': case 'm': case 'n': case 'o': case 'p':
    case 'q': case 'r': case 's': case 't': case 'u': case 'v':
    case 'w': case 'x': case 'y': case 'z': case '{': case '|':
    case '}': case '~': 
        goto state9;
    case '"': 
        goto state10;
    case '\\': 
        goto state18;
    }
    goto state0;

state5:
    // 5: ^I!^0
    m_notify->onParamEnd(ptr);
    goto state1;

state6:
    // 6: ^I!^I
    m_notify->onParamEnd(ptr);
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state1;
    case 9: case ' ': 
        goto state3;
    case '!': case '#': case '$': case '%': case '&': case '\'':
    case '(': case ')': case '*': case '+': case ',': case '-':
    case '.': case '/': case '0': case '1': case '2': case '3':
    case '4': case '5': case '6': case '7': case '8': case '9':
    case ':': case ';': case '<': case '=': case '>': case '?':
    case '@': case 'A': case 'B': case 'C': case 'D': case 'E':
    case 'F': case 'G': case 'H': case 'I': case 'J': case 'K':
    case 'L': case 'M': case 'N': case 'O': case 'P': case 'Q':
    case 'R': case 'S': case 'T': case 'U': case 'V': case 'W':
    case 'X': case 'Y': case 'Z': case '[': case ']': case '^':
    case '_': case '`': case 'a': case 'b': case 'c': case 'd':
    case 'e': case 'f': case 'g': case 'h': case 'i': case 'j':
    case 'k': case 'l': case 'm': case 'n': case 'o': case 'p':
    case 'q': case 'r': case 's': case 't': case 'u': case 'v':
    case 'w': case 'x': case 'y': case 'z': case '{': case '|':
    case '}': case '~': 
        goto state4;
    case '"': 
        goto state49;
    case '\\': 
        goto state50;
    }
    goto state0;

state9:
    // 9: ^I!^I^I!!
    // 51: ^I!!
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state5;
    case 9: case ' ': 
        goto state6;
    case '!': case '#': case '$': case '%': case '&': case '\'':
    case '(': case ')': case '*': case '+': case ',': case '-':
    case '.': case '/': case '0': case '1': case '2': case '3':
    case '4': case '5': case '6': case '7': case '8': case '9':
    case ':': case ';': case '<': case '=': case '>': case '?':
    case '@': case 'A': case 'B': case 'C': case 'D': case 'E':
    case 'F': case 'G': case 'H': case 'I': case 'J': case 'K':
    case 'L': case 'M': case 'N': case 'O': case 'P': case 'Q':
    case 'R': case 'S': case 'T': case 'U': case 'V': case 'W':
    case 'X': case 'Y': case 'Z': case '[': case ']': case '^':
    case '_': case '`': case 'a': case 'b': case 'c': case 'd':
    case 'e': case 'f': case 'g': case 'h': case 'i': case 'j':
    case 'k': case 'l': case 'm': case 'n': case 'o': case 'p':
    case 'q': case 'r': case 's': case 't': case 'u': case 'v':
    case 'w': case 'x': case 'y': case 'z': case '{': case '|':
    case '}': case '~': 
        goto state9;
    case '"': 
        goto state10;
    case '\\': 
        goto state18;
    }
    goto state0;

state10:
    // 10: ^I!^I^I!!"
    // 52: ^I!!"
    ch = *ptr++;
    switch (ch) {
    case 9: case ' ': case '!': case '#': case '$': case '%':
    case '&': case '\'': case '(': case ')': case '*': case '+':
    case ',': case '-': case '.': case '/': case '0': case '1':
    case '2': case '3': case '4': case '5': case '6': case '7':
    case '8': case '9': case ':': case ';': case '<': case '=':
    case '>': case '?': case '@': case 'A': case 'B': case 'C':
    case 'D': case 'E': case 'F': case 'G': case 'H': case 'I':
    case 'J': case 'K': case 'L': case 'M': case 'N': case 'O':
    case 'P': case 'Q': case 'R': case 'S': case 'T': case 'U':
    case 'V': case 'W': case 'X': case 'Y': case 'Z': case '[':
    case ']': case '^': case '_': case '`': case 'a': case 'b':
    case 'c': case 'd': case 'e': case 'f': case 'g': case 'h':
    case 'i': case 'j': case 'k': case 'l': case 'm': case 'n':
    case 'o': case 'p': case 'q': case 'r': case 's': case 't':
    case 'u': case 'v': case 'w': case 'x': case 'y': case 'z':
    case '{': case '|': case '}': case '~': 
        goto state11;
    case '"': 
        goto state43;
    case '\\': 
        goto state45;
    }
    goto state0;

state11:
    // 11: ^I!^I^I!!"^I
    // 23: ^I!^I^I!!"^I^I!^I""
    // 28: ^I!^I^I!!"^I^I!^I""!\"
    // 41: ^I!^I^I!!"!
    // 44: ^I!^I^I!!"""
    // 53: ^I!!"^I
    // 64: ^I!!"^I^I!^I""
    // 67: ^I!!"^I^I!^I""!\"
    // 80: ^I!!"!
    // 83: ^I!!"""
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state12;
    case 9: case ' ': 
        goto state13;
    case '!': case '#': case '$': case '%': case '&': case '\'':
    case '(': case ')': case '*': case '+': case ',': case '-':
    case '.': case '/': case '0': case '1': case '2': case '3':
    case '4': case '5': case '6': case '7': case '8': case '9':
    case ':': case ';': case '<': case '=': case '>': case '?':
    case '@': case 'A': case 'B': case 'C': case 'D': case 'E':
    case 'F': case 'G': case 'H': case 'I': case 'J': case 'K':
    case 'L': case 'M': case 'N': case 'O': case 'P': case 'Q':
    case 'R': case 'S': case 'T': case 'U': case 'V': case 'W':
    case 'X': case 'Y': case 'Z': case '[': case ']': case '^':
    case '_': case '`': case 'a': case 'b': case 'c': case 'd':
    case 'e': case 'f': case 'g': case 'h': case 'i': case 'j':
    case 'k': case 'l': case 'm': case 'n': case 'o': case 'p':
    case 'q': case 'r': case 's': case 't': case 'u': case 'v':
    case 'w': case 'x': case 'y': case 'z': case '{': case '|':
    case '}': case '~': 
        goto state14;
    case '"': 
        goto state16;
    case '\\': 
        goto state25;
    }
    goto state0;

state12:
    // 12: ^I!^I^I!!"^I^0
    m_notify->onParamEnd(ptr);
    m_notify->onParamEnd(ptr);
    goto state1;

state13:
    // 13: ^I!^I^I!!"^I^I
    // 15: ^I!^I^I!!"^I^I!^I
    // 54: ^I!!"^I^I
    // 56: ^I!!"^I^I!^I
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state5;
    case 9: case ' ': 
        goto state13;
    case '!': case '#': case '$': case '%': case '&': case '\'':
    case '(': case ')': case '*': case '+': case ',': case '-':
    case '.': case '/': case '0': case '1': case '2': case '3':
    case '4': case '5': case '6': case '7': case '8': case '9':
    case ':': case ';': case '<': case '=': case '>': case '?':
    case '@': case 'A': case 'B': case 'C': case 'D': case 'E':
    case 'F': case 'G': case 'H': case 'I': case 'J': case 'K':
    case 'L': case 'M': case 'N': case 'O': case 'P': case 'Q':
    case 'R': case 'S': case 'T': case 'U': case 'V': case 'W':
    case 'X': case 'Y': case 'Z': case '[': case ']': case '^':
    case '_': case '`': case 'a': case 'b': case 'c': case 'd':
    case 'e': case 'f': case 'g': case 'h': case 'i': case 'j':
    case 'k': case 'l': case 'm': case 'n': case 'o': case 'p':
    case 'q': case 'r': case 's': case 't': case 'u': case 'v':
    case 'w': case 'x': case 'y': case 'z': case '{': case '|':
    case '}': case '~': 
        goto state14;
    case '"': 
        goto state16;
    case '\\': 
        goto state25;
    }
    goto state0;

state14:
    // 14: ^I!^I^I!!"^I^I!
    // 24: ^I!^I^I!!"^I^I!^I""!
    // 55: ^I!!"^I^I!
    // 65: ^I!!"^I^I!^I""!
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state12;
    case 9: case ' ': 
        goto state13;
    case '!': case '#': case '$': case '%': case '&': case '\'':
    case '(': case ')': case '*': case '+': case ',': case '-':
    case '.': case '/': case '0': case '1': case '2': case '3':
    case '4': case '5': case '6': case '7': case '8': case '9':
    case ':': case ';': case '<': case '=': case '>': case '?':
    case '@': case 'A': case 'B': case 'C': case 'D': case 'E':
    case 'F': case 'G': case 'H': case 'I': case 'J': case 'K':
    case 'L': case 'M': case 'N': case 'O': case 'P': case 'Q':
    case 'R': case 'S': case 'T': case 'U': case 'V': case 'W':
    case 'X': case 'Y': case 'Z': case '[': case ']': case '^':
    case '_': case '`': case 'a': case 'b': case 'c': case 'd':
    case 'e': case 'f': case 'g': case 'h': case 'i': case 'j':
    case 'k': case 'l': case 'm': case 'n': case 'o': case 'p':
    case 'q': case 'r': case 's': case 't': case 'u': case 'v':
    case 'w': case 'x': case 'y': case 'z': case '{': case '|':
    case '}': case '~': 
        goto state14;
    case '"': 
        goto state16;
    case '\\': 
        goto state25;
    }
    goto state0;

state16:
    // 16: ^I!^I^I!!"^I^I!^I"
    // 36: ^I!^I^I!!"^I^I!^I"""
    // 57: ^I!!"^I^I!^I"
    // 75: ^I!!"^I^I!^I"""
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state5;
    case 9: case ' ': 
        goto state6;
    case '"': 
        goto state11;
    case '!': case '#': case '$': case '%': case '&': case '\'':
    case '(': case ')': case '*': case '+': case ',': case '-':
    case '.': case '/': case '0': case '1': case '2': case '3':
    case '4': case '5': case '6': case '7': case '8': case '9':
    case ':': case ';': case '<': case '=': case '>': case '?':
    case '@': case 'A': case 'B': case 'C': case 'D': case 'E':
    case 'F': case 'G': case 'H': case 'I': case 'J': case 'K':
    case 'L': case 'M': case 'N': case 'O': case 'P': case 'Q':
    case 'R': case 'S': case 'T': case 'U': case 'V': case 'W':
    case 'X': case 'Y': case 'Z': case '[': case ']': case '^':
    case '_': case '`': case 'a': case 'b': case 'c': case 'd':
    case 'e': case 'f': case 'g': case 'h': case 'i': case 'j':
    case 'k': case 'l': case 'm': case 'n': case 'o': case 'p':
    case 'q': case 'r': case 's': case 't': case 'u': case 'v':
    case 'w': case 'x': case 'y': case 'z': case '{': case '|':
    case '}': case '~': 
        goto state17;
    case '\\': 
        goto state32;
    }
    goto state0;

state17:
    // 17: ^I!^I^I!!"^I^I!^I"!
    // 19: ^I!^I^I!!"^I^I!^I"!\"
    // 58: ^I!!"^I^I!^I"!
    // 60: ^I!!"^I^I!^I"!\"
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state5;
    case 9: case ' ': 
        goto state6;
    case '!': case '#': case '$': case '%': case '&': case '\'':
    case '(': case ')': case '*': case '+': case ',': case '-':
    case '.': case '/': case '0': case '1': case '2': case '3':
    case '4': case '5': case '6': case '7': case '8': case '9':
    case ':': case ';': case '<': case '=': case '>': case '?':
    case '@': case 'A': case 'B': case 'C': case 'D': case 'E':
    case 'F': case 'G': case 'H': case 'I': case 'J': case 'K':
    case 'L': case 'M': case 'N': case 'O': case 'P': case 'Q':
    case 'R': case 'S': case 'T': case 'U': case 'V': case 'W':
    case 'X': case 'Y': case 'Z': case '[': case ']': case '^':
    case '_': case '`': case 'a': case 'b': case 'c': case 'd':
    case 'e': case 'f': case 'g': case 'h': case 'i': case 'j':
    case 'k': case 'l': case 'm': case 'n': case 'o': case 'p':
    case 'q': case 'r': case 's': case 't': case 'u': case 'v':
    case 'w': case 'x': case 'y': case 'z': case '{': case '|':
    case '}': case '~': 
        goto state9;
    case '"': 
        goto state10;
    case '\\': 
        goto state18;
    }
    goto state0;

state18:
    // 18: ^I!^I^I!!"^I^I!^I"!\ 
    // 20: ^I!^I^I!!"^I^I!^I"!\"\ 
    // 48: ^I!^I^I!!\ 
    // 59: ^I!!"^I^I!^I"!\ 
    // 61: ^I!!"^I^I!^I"!\"\ 
    // 87: ^I!!\ 
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state5;
    case 9: case ' ': 
        goto state6;
    case '!': case '#': case '$': case '%': case '&': case '\'':
    case '(': case ')': case '*': case '+': case ',': case '-':
    case '.': case '/': case '0': case '1': case '2': case '3':
    case '4': case '5': case '6': case '7': case '8': case '9':
    case ':': case ';': case '<': case '=': case '>': case '?':
    case '@': case 'A': case 'B': case 'C': case 'D': case 'E':
    case 'F': case 'G': case 'H': case 'I': case 'J': case 'K':
    case 'L': case 'M': case 'N': case 'O': case 'P': case 'Q':
    case 'R': case 'S': case 'T': case 'U': case 'V': case 'W':
    case 'X': case 'Y': case 'Z': case '[': case ']': case '^':
    case '_': case '`': case 'a': case 'b': case 'c': case 'd':
    case 'e': case 'f': case 'g': case 'h': case 'i': case 'j':
    case 'k': case 'l': case 'm': case 'n': case 'o': case 'p':
    case 'q': case 'r': case 's': case 't': case 'u': case 'v':
    case 'w': case 'x': case 'y': case 'z': case '{': case '|':
    case '}': case '~': 
        goto state9;
    case '"': 
        goto state17;
    case '\\': 
        goto state21;
    }
    goto state0;

state21:
    // 21: ^I!^I^I!!"^I^I!^I"!\"\\ 
    // 33: ^I!^I^I!!"^I^I!^I""!\"\\"\\ 
    // 62: ^I!!"^I^I!^I"!\"\\ 
    // 72: ^I!!"^I^I!^I""!\"\\"\\ 
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state5;
    case 9: case ' ': 
        goto state6;
    case '"': 
        goto state10;
    case '\\': 
        goto state22;
    }
    goto state0;

state22:
    // 22: ^I!^I^I!!"^I^I!^I"!\"\\\ 
    // 34: ^I!^I^I!!"^I^I!^I""!\"\\"\\\ 
    // 63: ^I!!"^I^I!^I"!\"\\\ 
    // 73: ^I!!"^I^I!^I""!\"\\"\\\ 
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state5;
    case 9: case ' ': 
        goto state6;
    case '"': 
        goto state17;
    case '\\': 
        goto state21;
    }
    goto state0;

state25:
    // 25: ^I!^I^I!!"^I^I!^I""!\ 
    // 29: ^I!^I^I!!"^I^I!^I""!\"\ 
    // 37: ^I!^I^I!!"^I^I!^I""\ 
    // 40: ^I!^I^I!!"^I^I!\ 
    // 42: ^I!^I^I!!"!\ 
    // 66: ^I!!"^I^I!^I""!\ 
    // 68: ^I!!"^I^I!^I""!\"\ 
    // 76: ^I!!"^I^I!^I""\ 
    // 79: ^I!!"^I^I!\ 
    // 81: ^I!!"!\ 
    ch = *ptr++;
    switch (ch) {
    case '"': 
        goto state11;
    case 0: 
        goto state12;
    case '!': case '#': case '$': case '%': case '&': case '\'':
    case '(': case ')': case '*': case '+': case ',': case '-':
    case '.': case '/': case '0': case '1': case '2': case '3':
    case '4': case '5': case '6': case '7': case '8': case '9':
    case ':': case ';': case '<': case '=': case '>': case '?':
    case '@': case 'A': case 'B': case 'C': case 'D': case 'E':
    case 'F': case 'G': case 'H': case 'I': case 'J': case 'K':
    case 'L': case 'M': case 'N': case 'O': case 'P': case 'Q':
    case 'R': case 'S': case 'T': case 'U': case 'V': case 'W':
    case 'X': case 'Y': case 'Z': case '[': case ']': case '^':
    case '_': case '`': case 'a': case 'b': case 'c': case 'd':
    case 'e': case 'f': case 'g': case 'h': case 'i': case 'j':
    case 'k': case 'l': case 'm': case 'n': case 'o': case 'p':
    case 'q': case 'r': case 's': case 't': case 'u': case 'v':
    case 'w': case 'x': case 'y': case 'z': case '{': case '|':
    case '}': case '~': 
        goto state14;
    case 9: case ' ': 
        goto state26;
    case '\\': 
        goto state30;
    }
    goto state0;

state26:
    // 26: ^I!^I^I!!"^I^I!^I""!\^I
    m_notify->onParamEnd(ptr);
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state1;
    case 9: case ' ': 
        goto state27;
    }
    goto state0;

state27:
    // 27: ^I!^I^I!!"^I^I!^I""!\^I^I
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state1;
    case 9: case ' ': 
        goto state27;
    }
    goto state0;

state30:
    // 30: ^I!^I^I!!"^I^I!^I""!\"\\ 
    // 38: ^I!^I^I!!"^I^I!^I""\\ 
    // 69: ^I!!"^I^I!^I""!\"\\ 
    // 77: ^I!!"^I^I!^I""\\ 
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state12;
    case 9: case ' ': 
        goto state26;
    case '"': 
        goto state31;
    case '\\': 
        goto state35;
    }
    goto state0;

state31:
    // 31: ^I!^I^I!!"^I^I!^I""!\"\\"
    // 70: ^I!!"^I^I!^I""!\"\\"
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state5;
    case 9: case ' ': 
        goto state6;
    case '"': 
        goto state10;
    case '!': case '#': case '$': case '%': case '&': case '\'':
    case '(': case ')': case '*': case '+': case ',': case '-':
    case '.': case '/': case '0': case '1': case '2': case '3':
    case '4': case '5': case '6': case '7': case '8': case '9':
    case ':': case ';': case '<': case '=': case '>': case '?':
    case '@': case 'A': case 'B': case 'C': case 'D': case 'E':
    case 'F': case 'G': case 'H': case 'I': case 'J': case 'K':
    case 'L': case 'M': case 'N': case 'O': case 'P': case 'Q':
    case 'R': case 'S': case 'T': case 'U': case 'V': case 'W':
    case 'X': case 'Y': case 'Z': case '[': case ']': case '^':
    case '_': case '`': case 'a': case 'b': case 'c': case 'd':
    case 'e': case 'f': case 'g': case 'h': case 'i': case 'j':
    case 'k': case 'l': case 'm': case 'n': case 'o': case 'p':
    case 'q': case 'r': case 's': case 't': case 'u': case 'v':
    case 'w': case 'x': case 'y': case 'z': case '{': case '|':
    case '}': case '~': 
        goto state17;
    case '\\': 
        goto state32;
    }
    goto state0;

state32:
    // 32: ^I!^I^I!!"^I^I!^I""!\"\\"\ 
    // 71: ^I!!"^I^I!^I""!\"\\"\ 
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state5;
    case 9: case ' ': 
        goto state6;
    case '!': case '"': case '#': case '$': case '%': case '&':
    case '\'': case '(': case ')': case '*': case '+': case ',':
    case '-': case '.': case '/': case '0': case '1': case '2':
    case '3': case '4': case '5': case '6': case '7': case '8':
    case '9': case ':': case ';': case '<': case '=': case '>':
    case '?': case '@': case 'A': case 'B': case 'C': case 'D':
    case 'E': case 'F': case 'G': case 'H': case 'I': case 'J':
    case 'K': case 'L': case 'M': case 'N': case 'O': case 'P':
    case 'Q': case 'R': case 'S': case 'T': case 'U': case 'V':
    case 'W': case 'X': case 'Y': case 'Z': case '[': case ']':
    case '^': case '_': case '`': case 'a': case 'b': case 'c':
    case 'd': case 'e': case 'f': case 'g': case 'h': case 'i':
    case 'j': case 'k': case 'l': case 'm': case 'n': case 'o':
    case 'p': case 'q': case 'r': case 's': case 't': case 'u':
    case 'v': case 'w': case 'x': case 'y': case 'z': case '{':
    case '|': case '}': case '~': 
        goto state17;
    case '\\': 
        goto state21;
    }
    goto state0;

state35:
    // 35: ^I!^I^I!!"^I^I!^I""!\"\\\ 
    // 39: ^I!^I^I!!"^I^I!^I""\\\ 
    // 74: ^I!!"^I^I!^I""!\"\\\ 
    // 78: ^I!!"^I^I!^I""\\\ 
    ch = *ptr++;
    switch (ch) {
    case '"': 
        goto state11;
    case 0: 
        goto state12;
    case 9: case ' ': 
        goto state26;
    case '\\': 
        goto state30;
    }
    goto state0;

state43:
    // 43: ^I!^I^I!!""
    // 82: ^I!!""
    ch = *ptr++;
    switch (ch) {
    case '"': 
        goto state11;
    }
    goto state0;

state45:
    // 45: ^I!^I^I!!"\ 
    // 84: ^I!!"\ 
    ch = *ptr++;
    switch (ch) {
    case '!': case '"': case '#': case '$': case '%': case '&':
    case '\'': case '(': case ')': case '*': case '+': case ',':
    case '-': case '.': case '/': case '0': case '1': case '2':
    case '3': case '4': case '5': case '6': case '7': case '8':
    case '9': case ':': case ';': case '<': case '=': case '>':
    case '?': case '@': case 'A': case 'B': case 'C': case 'D':
    case 'E': case 'F': case 'G': case 'H': case 'I': case 'J':
    case 'K': case 'L': case 'M': case 'N': case 'O': case 'P':
    case 'Q': case 'R': case 'S': case 'T': case 'U': case 'V':
    case 'W': case 'X': case 'Y': case 'Z': case '[': case ']':
    case '^': case '_': case '`': case 'a': case 'b': case 'c':
    case 'd': case 'e': case 'f': case 'g': case 'h': case 'i':
    case 'j': case 'k': case 'l': case 'm': case 'n': case 'o':
    case 'p': case 'q': case 'r': case 's': case 't': case 'u':
    case 'v': case 'w': case 'x': case 'y': case 'z': case '{':
    case '|': case '}': case '~': 
        goto state11;
    case '\\': 
        goto state46;
    }
    goto state0;

state46:
    // 46: ^I!^I^I!!"\\ 
    // 85: ^I!!"\\ 
    ch = *ptr++;
    switch (ch) {
    case '\\': 
        goto state47;
    }
    goto state0;

state47:
    // 47: ^I!^I^I!!"\\\ 
    // 86: ^I!!"\\\ 
    ch = *ptr++;
    switch (ch) {
    case '"': 
        goto state11;
    case '\\': 
        goto state46;
    }
    goto state0;

state49:
    // 49: ^I!^I^I"
    // 88: ^I"
    m_notify->onParamStart(ptr - 1);
    ch = *ptr++;
    switch (ch) {
    case 9: case ' ': case '!': case '#': case '$': case '%':
    case '&': case '\'': case '(': case ')': case '*': case '+':
    case ',': case '-': case '.': case '/': case '0': case '1':
    case '2': case '3': case '4': case '5': case '6': case '7':
    case '8': case '9': case ':': case ';': case '<': case '=':
    case '>': case '?': case '@': case 'A': case 'B': case 'C':
    case 'D': case 'E': case 'F': case 'G': case 'H': case 'I':
    case 'J': case 'K': case 'L': case 'M': case 'N': case 'O':
    case 'P': case 'Q': case 'R': case 'S': case 'T': case 'U':
    case 'V': case 'W': case 'X': case 'Y': case 'Z': case '[':
    case ']': case '^': case '_': case '`': case 'a': case 'b':
    case 'c': case 'd': case 'e': case 'f': case 'g': case 'h':
    case 'i': case 'j': case 'k': case 'l': case 'm': case 'n':
    case 'o': case 'p': case 'q': case 'r': case 's': case 't':
    case 'u': case 'v': case 'w': case 'x': case 'y': case 'z':
    case '{': case '|': case '}': case '~': 
        goto state11;
    case '"': 
        goto state43;
    case '\\': 
        goto state45;
    }
    goto state0;

state50:
    // 50: ^I!^I^I\ 
    // 89: ^I\ 
    m_notify->onParamStart(ptr - 1);
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state5;
    case 9: case ' ': 
        goto state6;
    case '!': case '"': case '#': case '$': case '%': case '&':
    case '\'': case '(': case ')': case '*': case '+': case ',':
    case '-': case '.': case '/': case '0': case '1': case '2':
    case '3': case '4': case '5': case '6': case '7': case '8':
    case '9': case ':': case ';': case '<': case '=': case '>':
    case '?': case '@': case 'A': case 'B': case 'C': case 'D':
    case 'E': case 'F': case 'G': case 'H': case 'I': case 'J':
    case 'K': case 'L': case 'M': case 'N': case 'O': case 'P':
    case 'Q': case 'R': case 'S': case 'T': case 'U': case 'V':
    case 'W': case 'X': case 'Y': case 'Z': case '[': case ']':
    case '^': case '_': case '`': case 'a': case 'b': case 'c':
    case 'd': case 'e': case 'f': case 'g': case 'h': case 'i':
    case 'j': case 'k': case 'l': case 'm': case 'n': case 'o':
    case 'p': case 'q': case 'r': case 's': case 't': case 'u':
    case 'v': case 'w': case 'x': case 'y': case 'z': case '{':
    case '|': case '}': case '~': 
        goto state17;
    case '\\': 
        goto state21;
    }
    goto state0;

state90:
    // 90: !
    m_notify->onParamStart(ptr - 1);
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state5;
    case 9: case ' ': 
        goto state6;
    case '!': case '#': case '$': case '%': case '&': case '\'':
    case '(': case ')': case '*': case '+': case ',': case '-':
    case '.': case '/': case '0': case '1': case '2': case '3':
    case '4': case '5': case '6': case '7': case '8': case '9':
    case ':': case ';': case '<': case '=': case '>': case '?':
    case '@': case 'A': case 'B': case 'C': case 'D': case 'E':
    case 'F': case 'G': case 'H': case 'I': case 'J': case 'K':
    case 'L': case 'M': case 'N': case 'O': case 'P': case 'Q':
    case 'R': case 'S': case 'T': case 'U': case 'V': case 'W':
    case 'X': case 'Y': case 'Z': case '[': case ']': case '^':
    case '_': case '`': case 'a': case 'b': case 'c': case 'd':
    case 'e': case 'f': case 'g': case 'h': case 'i': case 'j':
    case 'k': case 'l': case 'm': case 'n': case 'o': case 'p':
    case 'q': case 'r': case 's': case 't': case 'u': case 'v':
    case 'w': case 'x': case 'y': case 'z': case '{': case '|':
    case '}': case '~': 
        goto state91;
    case '"': 
        goto state92;
    case '\\': 
        goto state99;
    }
    goto state0;

state91:
    // 91: !!
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state5;
    case 9: case ' ': 
        goto state6;
    case '!': case '#': case '$': case '%': case '&': case '\'':
    case '(': case ')': case '*': case '+': case ',': case '-':
    case '.': case '/': case '0': case '1': case '2': case '3':
    case '4': case '5': case '6': case '7': case '8': case '9':
    case ':': case ';': case '<': case '=': case '>': case '?':
    case '@': case 'A': case 'B': case 'C': case 'D': case 'E':
    case 'F': case 'G': case 'H': case 'I': case 'J': case 'K':
    case 'L': case 'M': case 'N': case 'O': case 'P': case 'Q':
    case 'R': case 'S': case 'T': case 'U': case 'V': case 'W':
    case 'X': case 'Y': case 'Z': case '[': case ']': case '^':
    case '_': case '`': case 'a': case 'b': case 'c': case 'd':
    case 'e': case 'f': case 'g': case 'h': case 'i': case 'j':
    case 'k': case 'l': case 'm': case 'n': case 'o': case 'p':
    case 'q': case 'r': case 's': case 't': case 'u': case 'v':
    case 'w': case 'x': case 'y': case 'z': case '{': case '|':
    case '}': case '~': 
        goto state91;
    case '"': 
        goto state92;
    case '\\': 
        goto state99;
    }
    goto state0;

state92:
    // 92: !!"
    ch = *ptr++;
    switch (ch) {
    case 9: case ' ': case '!': case '#': case '$': case '%':
    case '&': case '\'': case '(': case ')': case '*': case '+':
    case ',': case '-': case '.': case '/': case '0': case '1':
    case '2': case '3': case '4': case '5': case '6': case '7':
    case '8': case '9': case ':': case ';': case '<': case '=':
    case '>': case '?': case '@': case 'A': case 'B': case 'C':
    case 'D': case 'E': case 'F': case 'G': case 'H': case 'I':
    case 'J': case 'K': case 'L': case 'M': case 'N': case 'O':
    case 'P': case 'Q': case 'R': case 'S': case 'T': case 'U':
    case 'V': case 'W': case 'X': case 'Y': case 'Z': case '[':
    case ']': case '^': case '_': case '`': case 'a': case 'b':
    case 'c': case 'd': case 'e': case 'f': case 'g': case 'h':
    case 'i': case 'j': case 'k': case 'l': case 'm': case 'n':
    case 'o': case 'p': case 'q': case 'r': case 's': case 't':
    case 'u': case 'v': case 'w': case 'x': case 'y': case 'z':
    case '{': case '|': case '}': case '~': 
        goto state93;
    case '"': 
        goto state122;
    case '\\': 
        goto state123;
    }
    goto state0;

state93:
    // 93: !!"^I
    // 104: !!"^I^I!^I""
    // 107: !!"^I^I!^I""!\"
    // 120: !!"!
    ch = *ptr++;
    switch (ch) {
    case 9: case ' ': 
        goto state94;
    case '!': case '#': case '$': case '%': case '&': case '\'':
    case '(': case ')': case '*': case '+': case ',': case '-':
    case '.': case '/': case '0': case '1': case '2': case '3':
    case '4': case '5': case '6': case '7': case '8': case '9':
    case ':': case ';': case '<': case '=': case '>': case '?':
    case '@': case 'A': case 'B': case 'C': case 'D': case 'E':
    case 'F': case 'G': case 'H': case 'I': case 'J': case 'K':
    case 'L': case 'M': case 'N': case 'O': case 'P': case 'Q':
    case 'R': case 'S': case 'T': case 'U': case 'V': case 'W':
    case 'X': case 'Y': case 'Z': case '[': case ']': case '^':
    case '_': case '`': case 'a': case 'b': case 'c': case 'd':
    case 'e': case 'f': case 'g': case 'h': case 'i': case 'j':
    case 'k': case 'l': case 'm': case 'n': case 'o': case 'p':
    case 'q': case 'r': case 's': case 't': case 'u': case 'v':
    case 'w': case 'x': case 'y': case 'z': case '{': case '|':
    case '}': case '~': 
        goto state95;
    case '"': 
        goto state97;
    case '\\': 
        goto state106;
    }
    goto state0;

state94:
    // 94: !!"^I^I
    // 96: !!"^I^I!^I
    ch = *ptr++;
    switch (ch) {
    case 9: case ' ': 
        goto state94;
    case '!': case '#': case '$': case '%': case '&': case '\'':
    case '(': case ')': case '*': case '+': case ',': case '-':
    case '.': case '/': case '0': case '1': case '2': case '3':
    case '4': case '5': case '6': case '7': case '8': case '9':
    case ':': case ';': case '<': case '=': case '>': case '?':
    case '@': case 'A': case 'B': case 'C': case 'D': case 'E':
    case 'F': case 'G': case 'H': case 'I': case 'J': case 'K':
    case 'L': case 'M': case 'N': case 'O': case 'P': case 'Q':
    case 'R': case 'S': case 'T': case 'U': case 'V': case 'W':
    case 'X': case 'Y': case 'Z': case '[': case ']': case '^':
    case '_': case '`': case 'a': case 'b': case 'c': case 'd':
    case 'e': case 'f': case 'g': case 'h': case 'i': case 'j':
    case 'k': case 'l': case 'm': case 'n': case 'o': case 'p':
    case 'q': case 'r': case 's': case 't': case 'u': case 'v':
    case 'w': case 'x': case 'y': case 'z': case '{': case '|':
    case '}': case '~': 
        goto state95;
    case '"': 
        goto state97;
    case '\\': 
        goto state106;
    }
    goto state0;

state95:
    // 95: !!"^I^I!
    // 105: !!"^I^I!^I""!
    ch = *ptr++;
    switch (ch) {
    case 9: case ' ': 
        goto state94;
    case '!': case '#': case '$': case '%': case '&': case '\'':
    case '(': case ')': case '*': case '+': case ',': case '-':
    case '.': case '/': case '0': case '1': case '2': case '3':
    case '4': case '5': case '6': case '7': case '8': case '9':
    case ':': case ';': case '<': case '=': case '>': case '?':
    case '@': case 'A': case 'B': case 'C': case 'D': case 'E':
    case 'F': case 'G': case 'H': case 'I': case 'J': case 'K':
    case 'L': case 'M': case 'N': case 'O': case 'P': case 'Q':
    case 'R': case 'S': case 'T': case 'U': case 'V': case 'W':
    case 'X': case 'Y': case 'Z': case '[': case ']': case '^':
    case '_': case '`': case 'a': case 'b': case 'c': case 'd':
    case 'e': case 'f': case 'g': case 'h': case 'i': case 'j':
    case 'k': case 'l': case 'm': case 'n': case 'o': case 'p':
    case 'q': case 'r': case 's': case 't': case 'u': case 'v':
    case 'w': case 'x': case 'y': case 'z': case '{': case '|':
    case '}': case '~': 
        goto state95;
    case '"': 
        goto state97;
    case '\\': 
        goto state106;
    }
    goto state0;

state97:
    // 97: !!"^I^I!^I"
    // 115: !!"^I^I!^I"""
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state5;
    case 9: case ' ': 
        goto state6;
    case '"': 
        goto state93;
    case '!': case '#': case '$': case '%': case '&': case '\'':
    case '(': case ')': case '*': case '+': case ',': case '-':
    case '.': case '/': case '0': case '1': case '2': case '3':
    case '4': case '5': case '6': case '7': case '8': case '9':
    case ':': case ';': case '<': case '=': case '>': case '?':
    case '@': case 'A': case 'B': case 'C': case 'D': case 'E':
    case 'F': case 'G': case 'H': case 'I': case 'J': case 'K':
    case 'L': case 'M': case 'N': case 'O': case 'P': case 'Q':
    case 'R': case 'S': case 'T': case 'U': case 'V': case 'W':
    case 'X': case 'Y': case 'Z': case '[': case ']': case '^':
    case '_': case '`': case 'a': case 'b': case 'c': case 'd':
    case 'e': case 'f': case 'g': case 'h': case 'i': case 'j':
    case 'k': case 'l': case 'm': case 'n': case 'o': case 'p':
    case 'q': case 'r': case 's': case 't': case 'u': case 'v':
    case 'w': case 'x': case 'y': case 'z': case '{': case '|':
    case '}': case '~': 
        goto state98;
    case '\\': 
        goto state111;
    }
    goto state0;

state98:
    // 98: !!"^I^I!^I"!
    // 100: !!"^I^I!^I"!\"
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state5;
    case 9: case ' ': 
        goto state6;
    case '!': case '#': case '$': case '%': case '&': case '\'':
    case '(': case ')': case '*': case '+': case ',': case '-':
    case '.': case '/': case '0': case '1': case '2': case '3':
    case '4': case '5': case '6': case '7': case '8': case '9':
    case ':': case ';': case '<': case '=': case '>': case '?':
    case '@': case 'A': case 'B': case 'C': case 'D': case 'E':
    case 'F': case 'G': case 'H': case 'I': case 'J': case 'K':
    case 'L': case 'M': case 'N': case 'O': case 'P': case 'Q':
    case 'R': case 'S': case 'T': case 'U': case 'V': case 'W':
    case 'X': case 'Y': case 'Z': case '[': case ']': case '^':
    case '_': case '`': case 'a': case 'b': case 'c': case 'd':
    case 'e': case 'f': case 'g': case 'h': case 'i': case 'j':
    case 'k': case 'l': case 'm': case 'n': case 'o': case 'p':
    case 'q': case 'r': case 's': case 't': case 'u': case 'v':
    case 'w': case 'x': case 'y': case 'z': case '{': case '|':
    case '}': case '~': 
        goto state91;
    case '"': 
        goto state92;
    case '\\': 
        goto state99;
    }
    goto state0;

state99:
    // 99: !!"^I^I!^I"!\ 
    // 101: !!"^I^I!^I"!\"\ 
    // 126: !!\ 
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state5;
    case 9: case ' ': 
        goto state6;
    case '!': case '#': case '$': case '%': case '&': case '\'':
    case '(': case ')': case '*': case '+': case ',': case '-':
    case '.': case '/': case '0': case '1': case '2': case '3':
    case '4': case '5': case '6': case '7': case '8': case '9':
    case ':': case ';': case '<': case '=': case '>': case '?':
    case '@': case 'A': case 'B': case 'C': case 'D': case 'E':
    case 'F': case 'G': case 'H': case 'I': case 'J': case 'K':
    case 'L': case 'M': case 'N': case 'O': case 'P': case 'Q':
    case 'R': case 'S': case 'T': case 'U': case 'V': case 'W':
    case 'X': case 'Y': case 'Z': case '[': case ']': case '^':
    case '_': case '`': case 'a': case 'b': case 'c': case 'd':
    case 'e': case 'f': case 'g': case 'h': case 'i': case 'j':
    case 'k': case 'l': case 'm': case 'n': case 'o': case 'p':
    case 'q': case 'r': case 's': case 't': case 'u': case 'v':
    case 'w': case 'x': case 'y': case 'z': case '{': case '|':
    case '}': case '~': 
        goto state91;
    case '"': 
        goto state98;
    case '\\': 
        goto state102;
    }
    goto state0;

state102:
    // 102: !!"^I^I!^I"!\"\\ 
    // 112: !!"^I^I!^I""!\"\\"\\ 
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state5;
    case 9: case ' ': 
        goto state6;
    case '"': 
        goto state92;
    case '\\': 
        goto state103;
    }
    goto state0;

state103:
    // 103: !!"^I^I!^I"!\"\\\ 
    // 113: !!"^I^I!^I""!\"\\"\\\ 
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state5;
    case 9: case ' ': 
        goto state6;
    case '"': 
        goto state98;
    case '\\': 
        goto state102;
    }
    goto state0;

state106:
    // 106: !!"^I^I!^I""!\ 
    // 108: !!"^I^I!^I""!\"\ 
    // 116: !!"^I^I!^I""\ 
    // 119: !!"^I^I!\ 
    // 121: !!"!\ 
    ch = *ptr++;
    switch (ch) {
    case '"': 
        goto state93;
    case '!': case '#': case '$': case '%': case '&': case '\'':
    case '(': case ')': case '*': case '+': case ',': case '-':
    case '.': case '/': case '0': case '1': case '2': case '3':
    case '4': case '5': case '6': case '7': case '8': case '9':
    case ':': case ';': case '<': case '=': case '>': case '?':
    case '@': case 'A': case 'B': case 'C': case 'D': case 'E':
    case 'F': case 'G': case 'H': case 'I': case 'J': case 'K':
    case 'L': case 'M': case 'N': case 'O': case 'P': case 'Q':
    case 'R': case 'S': case 'T': case 'U': case 'V': case 'W':
    case 'X': case 'Y': case 'Z': case '[': case ']': case '^':
    case '_': case '`': case 'a': case 'b': case 'c': case 'd':
    case 'e': case 'f': case 'g': case 'h': case 'i': case 'j':
    case 'k': case 'l': case 'm': case 'n': case 'o': case 'p':
    case 'q': case 'r': case 's': case 't': case 'u': case 'v':
    case 'w': case 'x': case 'y': case 'z': case '{': case '|':
    case '}': case '~': 
        goto state95;
    case '\\': 
        goto state109;
    }
    goto state0;

state109:
    // 109: !!"^I^I!^I""!\"\\ 
    // 117: !!"^I^I!^I""\\ 
    ch = *ptr++;
    switch (ch) {
    case '"': 
        goto state110;
    case '\\': 
        goto state114;
    }
    goto state0;

state110:
    // 110: !!"^I^I!^I""!\"\\"
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state5;
    case 9: case ' ': 
        goto state6;
    case '"': 
        goto state92;
    case '!': case '#': case '$': case '%': case '&': case '\'':
    case '(': case ')': case '*': case '+': case ',': case '-':
    case '.': case '/': case '0': case '1': case '2': case '3':
    case '4': case '5': case '6': case '7': case '8': case '9':
    case ':': case ';': case '<': case '=': case '>': case '?':
    case '@': case 'A': case 'B': case 'C': case 'D': case 'E':
    case 'F': case 'G': case 'H': case 'I': case 'J': case 'K':
    case 'L': case 'M': case 'N': case 'O': case 'P': case 'Q':
    case 'R': case 'S': case 'T': case 'U': case 'V': case 'W':
    case 'X': case 'Y': case 'Z': case '[': case ']': case '^':
    case '_': case '`': case 'a': case 'b': case 'c': case 'd':
    case 'e': case 'f': case 'g': case 'h': case 'i': case 'j':
    case 'k': case 'l': case 'm': case 'n': case 'o': case 'p':
    case 'q': case 'r': case 's': case 't': case 'u': case 'v':
    case 'w': case 'x': case 'y': case 'z': case '{': case '|':
    case '}': case '~': 
        goto state98;
    case '\\': 
        goto state111;
    }
    goto state0;

state111:
    // 111: !!"^I^I!^I""!\"\\"\ 
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state5;
    case 9: case ' ': 
        goto state6;
    case '!': case '"': case '#': case '$': case '%': case '&':
    case '\'': case '(': case ')': case '*': case '+': case ',':
    case '-': case '.': case '/': case '0': case '1': case '2':
    case '3': case '4': case '5': case '6': case '7': case '8':
    case '9': case ':': case ';': case '<': case '=': case '>':
    case '?': case '@': case 'A': case 'B': case 'C': case 'D':
    case 'E': case 'F': case 'G': case 'H': case 'I': case 'J':
    case 'K': case 'L': case 'M': case 'N': case 'O': case 'P':
    case 'Q': case 'R': case 'S': case 'T': case 'U': case 'V':
    case 'W': case 'X': case 'Y': case 'Z': case '[': case ']':
    case '^': case '_': case '`': case 'a': case 'b': case 'c':
    case 'd': case 'e': case 'f': case 'g': case 'h': case 'i':
    case 'j': case 'k': case 'l': case 'm': case 'n': case 'o':
    case 'p': case 'q': case 'r': case 's': case 't': case 'u':
    case 'v': case 'w': case 'x': case 'y': case 'z': case '{':
    case '|': case '}': case '~': 
        goto state98;
    case '\\': 
        goto state102;
    }
    goto state0;

state114:
    // 114: !!"^I^I!^I""!\"\\\ 
    // 118: !!"^I^I!^I""\\\ 
    ch = *ptr++;
    switch (ch) {
    case '"': 
        goto state93;
    case '\\': 
        goto state109;
    }
    goto state0;

state122:
    // 122: !!""
    ch = *ptr++;
    switch (ch) {
    case '"': 
        goto state93;
    }
    goto state0;

state123:
    // 123: !!"\ 
    ch = *ptr++;
    switch (ch) {
    case '!': case '"': case '#': case '$': case '%': case '&':
    case '\'': case '(': case ')': case '*': case '+': case ',':
    case '-': case '.': case '/': case '0': case '1': case '2':
    case '3': case '4': case '5': case '6': case '7': case '8':
    case '9': case ':': case ';': case '<': case '=': case '>':
    case '?': case '@': case 'A': case 'B': case 'C': case 'D':
    case 'E': case 'F': case 'G': case 'H': case 'I': case 'J':
    case 'K': case 'L': case 'M': case 'N': case 'O': case 'P':
    case 'Q': case 'R': case 'S': case 'T': case 'U': case 'V':
    case 'W': case 'X': case 'Y': case 'Z': case '[': case ']':
    case '^': case '_': case '`': case 'a': case 'b': case 'c':
    case 'd': case 'e': case 'f': case 'g': case 'h': case 'i':
    case 'j': case 'k': case 'l': case 'm': case 'n': case 'o':
    case 'p': case 'q': case 'r': case 's': case 't': case 'u':
    case 'v': case 'w': case 'x': case 'y': case 'z': case '{':
    case '|': case '}': case '~': 
        goto state93;
    case '\\': 
        goto state124;
    }
    goto state0;

state124:
    // 124: !!"\\ 
    ch = *ptr++;
    switch (ch) {
    case '\\': 
        goto state125;
    }
    goto state0;

state125:
    // 125: !!"\\\ 
    ch = *ptr++;
    switch (ch) {
    case '"': 
        goto state93;
    case '\\': 
        goto state124;
    }
    goto state0;

state127:
    // 127: "
    m_notify->onParamStart(ptr - 1);
    ch = *ptr++;
    switch (ch) {
    case 9: case ' ': case '!': case '#': case '$': case '%':
    case '&': case '\'': case '(': case ')': case '*': case '+':
    case ',': case '-': case '.': case '/': case '0': case '1':
    case '2': case '3': case '4': case '5': case '6': case '7':
    case '8': case '9': case ':': case ';': case '<': case '=':
    case '>': case '?': case '@': case 'A': case 'B': case 'C':
    case 'D': case 'E': case 'F': case 'G': case 'H': case 'I':
    case 'J': case 'K': case 'L': case 'M': case 'N': case 'O':
    case 'P': case 'Q': case 'R': case 'S': case 'T': case 'U':
    case 'V': case 'W': case 'X': case 'Y': case 'Z': case '[':
    case ']': case '^': case '_': case '`': case 'a': case 'b':
    case 'c': case 'd': case 'e': case 'f': case 'g': case 'h':
    case 'i': case 'j': case 'k': case 'l': case 'm': case 'n':
    case 'o': case 'p': case 'q': case 'r': case 's': case 't':
    case 'u': case 'v': case 'w': case 'x': case 'y': case 'z':
    case '{': case '|': case '}': case '~': 
        goto state93;
    case '"': 
        goto state122;
    case '\\': 
        goto state123;
    }
    goto state0;

state128:
    // 128: \ 
    m_notify->onParamStart(ptr - 1);
    ch = *ptr++;
    switch (ch) {
    case 0: 
        goto state5;
    case 9: case ' ': 
        goto state6;
    case '!': case '"': case '#': case '$': case '%': case '&':
    case '\'': case '(': case ')': case '*': case '+': case ',':
    case '-': case '.': case '/': case '0': case '1': case '2':
    case '3': case '4': case '5': case '6': case '7': case '8':
    case '9': case ':': case ';': case '<': case '=': case '>':
    case '?': case '@': case 'A': case 'B': case 'C': case 'D':
    case 'E': case 'F': case 'G': case 'H': case 'I': case 'J':
    case 'K': case 'L': case 'M': case 'N': case 'O': case 'P':
    case 'Q': case 'R': case 'S': case 'T': case 'U': case 'V':
    case 'W': case 'X': case 'Y': case 'Z': case '[': case ']':
    case '^': case '_': case '`': case 'a': case 'b': case 'c':
    case 'd': case 'e': case 'f': case 'g': case 'h': case 'i':
    case 'j': case 'k': case 'l': case 'm': case 'n': case 'o':
    case 'p': case 'q': case 'r': case 's': case 't': case 'u':
    case 'v': case 'w': case 'x': case 'y': case 'z': case '{':
    case '|': case '}': case '~': 
        goto state98;
    case '\\': 
        goto state102;
    }
    goto state0;
}

