# Copyright Glen Knowles 2021 - 2022.
# Distributed under the Boost Software License, Version 1.0.
#
# github-build.yml

name: build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  workflow_dispatch: {}

jobs:
  build-win:
    strategy:
      matrix:
        platform: [x64]
        configuration: [Debug, Release]
        toolset: [v143]
        image: [windows-2022]
    runs-on: ${{matrix.image}}
    defaults:
      run:
        shell: cmd
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        if not exist "conf\app.xml" copy "conf\app.xml.sample" "conf\app.xml"
        md build
        cd build
        if "${{matrix.toolset}}" == "v143" (
          set generator=Visual Studio 17 2022
        ) else (
          set generator=Visual Studio 16 2019
        )
        cmake .. -G "%generator%" -A ${{matrix.platform}} -T ${{matrix.toolset}}
        cmake . -DCMAKE_BUILD_TYPE=${{matrix.configuration}} -DCMAKE_INSTALL_PREFIX=publish -DINSTALL_LIBS:BOOL=ON
        cmake --build . --target install --config ${{matrix.configuration}}
        cd publish
        :: 7z a dimcli-latest.zip include lib

    - name: Test
      working-directory: ${{github.workspace}}
      run: |
        for %%t in (
            bin\bitview-t
            bin\charbuf-t
            bin\file-t
            bin\glob-t
            bin\hpack-t
            "bin\http-t --test"
            "bin\json-t --test"
            bin\list-t
            bin\math-t
            bin\msgpack-t
            "bin\pargen --test"
            bin\path-t
            bin\str-t
            "bin\strtrie-t --test"
            bin\time-t
            bin\tokentable-t
            bin\uset-t
            "bin\xml --test"
        ) do (
            %%~t
            if errorlevel 1 goto :eof
        )
