# Copyright Glen Knowles 2021.
# Distributed under the Boost Software License, Version 1.0.
#
# github-build.yml

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  build-win:
    strategy:
      matrix:
        platform: [x64]
        configuration: [Debug, Release]
        toolset: [v143]
        image: [windows-2022]
    runs-on: ${{matrix.image}}
    defaults:
      run:
        shell: cmd
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        md build
        cd build
        if "${{matrix.toolset}}" == "v143" (
          set generator=Visual Studio 17 2022
        ) else (
          set generator=Visual Studio 16 2019
        )
        cmake .. -G "%generator%" -A ${{matrix.platform}} -T ${{matrix.toolset}}
        cmake . -DCMAKE_BUILD_TYPE=${{matrix.configuration}} -DCMAKE_INSTALL_PREFIX=publish -DINSTALL_LIBS:BOOL=ON
        cmake --build . --target install --config ${{matrix.configuration}}
        cd publish
        :: 7z a dimcli-latest.zip include lib

    - name: Test
      working-directory: ${{github.workspace}}
      run: |
        bin\bitview-t
        bin\charbuf-t
        bin\file-t
        bin\hpack-t
        bin\http-t
        bin\json-t --test
        bin\list-t
        bin\math-t
        bin\msgpack-t
        bin\pargen --test
        bin\path-t
        bin\str-t
        bin\strtrie-t --test
        bin\time-t
        bin\tokentable-t
        bin\uset-t
        bin\xml --test
